#@ load("@ytt:data", "data")

#@ load("vendor/pipeline-fragments.lib.yml",
#@   "nodejs_check_code",
#@   "nodejs_audit",
#@   "build_edge_image",
#@   "repo_resource",
#@   "nodejs_deps_resource",
#@   "install_nodejs_deps",
#@   "open_charts_pr",
#@   "deps_version_resource",
#@   "bundled_deps_resource",
#@   "gh_release_resource",
#@   "charts_repo_bot_branch",
#@   "version_resource",
#@   "versioned_image_resource",
#@   "charts_repo_resource",
#@   "release_task_image_config",
#@   "edge_image_resource",
#@   "public_docker_registry",
#@   "pipeline_tasks_resource",
#@   "nodejs_task_image_config",
#@   "slack_resource",
#@   "gcr_resource_type",
#@   "slack_resource_type")

jobs:
- #@ nodejs_check_code()
- #@ nodejs_audit()
- #@ install_nodejs_deps(pckgMgr="pnpm")

resources:
- #@ repo_resource()
- #@ nodejs_deps_resource(pckgMgr="pnpm")
- #@ pipeline_tasks_resource()
- #@ deps_version_resource()
- #@ bundled_deps_resource()
- #@ slack_resource()

resource_types:
- #@ gcr_resource_type()
- #@ slack_resource_type()
- name: npm
  type: docker-image
  source:
    repository: timotto/concourse-npm-resource
