#@ load("@ytt:data", "data")
#@ load("vendor/pipeline-fragments.lib.yml",
#@   "private_docker_registry",
#@   "release_task_image_config",
#@   "build_edge_image",
#@   "edge_image_resource",

#@   "nodejs_check_code",
#@   "nodejs_audit",
#@   "install_nodejs_deps",
#@   "repo_resource",
#@   "nodejs_deps_resource",
#@   "pipeline_tasks_resource",
#@   "deps_version_resource",
#@   "bundled_deps_resource",
#@   "slack_resource",
#@   "gcr_resource_type",
#@   "slack_resource_type")

jobs:
- #@ nodejs_check_code()
- #@ nodejs_audit()
- #@ install_nodejs_deps(pckgMgr="pnpm")
- #@ build_edge_image()

resources:
- #@ repo_resource()
- #@ nodejs_deps_resource(pckgMgr="pnpm")
- #@ pipeline_tasks_resource()
- #@ deps_version_resource()
- #@ bundled_deps_resource()
- #@ slack_resource()
- #@ edge_image_resource()

resource_types:
- #@ gcr_resource_type()
- #@ slack_resource_type()
- name: npm
  type: docker-image
  source:
    repository: timotto/concourse-npm-resource
