name: "Unit tests"

on:
  pull_request:
    branches: [main]
    
jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Install dependencies inside nix develop
        run: nix develop -c pnpm install

      - name: Run check code
        run: nix develop -c pnpm test
